### ISSUE TITLE
PIPlayerApplet: null BLOCK_NAME

### ISSUE THREAD

**Issue by baranan** [ProjectImplicit/PIPlayer#28]
I sent to the server data with empty stimuli and empty media. The response was 500 with this message:
java.sql.SQLException: ORA-20000: yuiat_admin_pkg.insert_applet_data ORA-01400: cannot insert NULL into ("YUIAT_RESEARCH_ADMIN"."YUIAT_APPLET_DATA"."BLOCK_NAME") Session: 666883 Block:  Trial: 11

I assume that PIPlayerApplet uses the stimuli field for BLOCK_NAME. I don't think we want to prevent people from not logging their stimuli. If stimuli is empty, enter an empty string, or the string "null" (whatever is possible). The same is true for whatever you do with the media field (I guess it goes to trial_name).

**Comment by eladzlot** [comment]
@andrewdzik can we close this?

**Comment by eladzlot** [comment]
Closing for lack of interest as part of an issue triage. If this comes up again, we can reopen.
