### ISSUE TITLE
Typos in PIP Documentation

### ISSUE THREAD

**Issue by calvinklai** [ProjectImplicit/PIPlayer#44]
Some misc.  typos I caught:

http://projectimplicit.github.io/PIPlayer/0.3/examples/iatDocco.html "Pleasaure"

http://projectimplicit.github.io/PIPlayer/0.3/examples/ampDocco.html "Pleasent" (in 3 places)
http://projectimplicit.github.io/PIPlayer/0.3/examples/evaluative_primingDocco.html "Pleasent (in 22 places)

**Comment by calvinklai** [comment]
http://projectimplicit.github.io/PIPlayer/0.3/examples/gnatPlay.html "Pleasaure"

**Comment by eladzlot** [comment]
Thanks. Fixed now.
